### ISSUE TITLE
Packages still missing precompiles

### ISSUE THREAD

**Issue by untoreh** [panifie/PingPong.jl#21]
- [x] Watchers
- [x] Sim/Paper/Live mode
- [ ] Cli
- [ ] Engine
- [ ] Executors
- [ ] Instances
- [ ] Collections
- [x] OrderTypes
- [ ] Simulations
- [x] Stats
- [x] Strategies
- [x] Plotting
- [x] Exchanges
- [x] Fetch

**Comment by panbonker** [comment]
other precompile directives are in the main PingPong pkg since the other pkgs are mostly middleware
