### ISSUE TITLE
Convert some Trality examples

### ISSUE THREAD

**Issue by c0indev3l** [panifie/PingPong.jl#25]
Hello,

Trality, a Python crypto trading bot will stop. See https://www.trality.com/blog/trality-winding-down-product
I'm considering moving to Julia and an open source trading environment.
Converting some Trality examples to PingPong.jl could help to attract new users.
Here are some examples https://gist.github.com/c0indev3l/855381f07865dfca079e8252e736ae35
and documentation https://docs.trality.com/

Kind regards

**Comment by panbonker** [comment]
The bot doesn't manage data for you, see here https://github.com/panifie/PingPong.jl/issues/16

To access ohlcv data from a strategy you can do so from an `AssetInstance` variable:
`ai.data` is a dict where keys are timeframes and values are dataframes of ohlcv data. The first pair should always be the smallest timeframe of the strategy, which is the one you monitor for updates (during paper and live mode). The rest of the dataframes in the dict (if any) should be resampled (downsampled) from the smaller one.
For convenience the "main" timeframe of the asset instance (and strategy) can be accessed with the ohlcv property (`ai.ohlcv`).

During backtest you need to pre populate the dataframes your self. There are utilities in the bot to download data in different ways.
see here a function to load data from the `Scrapers` module https://github.com/panifie/PingPong.jl/blob/master/PingPong/test/env.jl
and here a function to load a strategy, and fill its assets with stub data https://github.com/panifie/PingPong.jl/blob/master/PingPong/test/env_strat.jl

During paper/live you create a `Watcher` from the `Watchers` module and use the watcher _view_ which is a dict of dataframes (ohlcv) and use those dataframes in your strategy universe, see here where we create the watcher and fill the strategy universe with the data monitored by the watcher https://github.com/panifie/PingPong.jl/blob/2ef17a8b1b4915c74389082e798cced395631edd/user/strategies/Example.jl#L26-L28

If you want to execute something at specified interval the simplest approach is to just track timestamps:
```julia
isstale15m(s, ts) = ts - attr(s, :job_15m, DateTime(0)) > tf"15m"
job15m(s, ts, ats) = (println("Running job every 15m"); setattr!(s, :job_15m, ts))

function ping!(s, ts::DateTime, args...)
    ats = available(ts)
    isstale15m(s, ts) && job15m(s, ts, ats)
end

```

A fancier approach would involve using either Rocket.jl or DiscreteEvents.jl but I don't think that's necessary, If I implement it it would be more like an optional feature where you can call a `pong!`  function and get a virtual clock to which you can subscribe functions that run at a particular time, and that clock would be replaced with a realtime clock in paper/live mode.
