### ISSUE TITLE
UndefVarError: `scr` not defined

### ISSUE THREAD

**Issue by femtotrader** [panifie/PingPong.jl#30]
Hello,

According doc

https://github.com/panifie/PingPong.jl/blame/3ef7dd4cf48a9ff956ec53d3b4cf732fd8e18675/docs/src/index.md#L86

But

    julia> const bn = scr.BinanceData
    ERROR: UndefVarError: `scr` not defined

Any idea how to fix this?

**Comment by panbonker** [comment]
I assume you didn't know that `scr` is just a shorthand for the `Scrapers` module, so just import it `using Scrapers: Scrapers as scr`
