### ISSUE TITLE
[Help] How to debug(stepinto) in vscode?

### ISSUE THREAD

**Issue by janckerchen** [panifie/PingPong.jl#51]
I tried debugging the code in VS Code, but I can't step into the code either by setting breakpoints or using the `@enter` macro. What configuration is needed?
(The environment variables in `.envrc` can be inherited by launching VS Code from the terminal.)

```julia
using PingPong
using Data: Data as data
using SimMode: SimMode as sm

@environment!
s = st.strategy(:SimpleStrategy, exchange=:binance) 

# step into failed
@enter fetch_ohlcv(s, from=-1000) 
# step into failed
@enter load_ohlcv(s)
# step into failed
@enter sm.start!(s)
```

**Comment by janckerchen** [comment]
Removing `julia.debuggerDefaultCompiled` from settings.json of vscode and keeping the default configuration can resolve this issue. `ALL_MODULES_EXCEPT_MAIN` prevents the debugger from entering all modules except the main program.

```json
"julia.debuggerDefaultCompiled": [    
        "ALL_MODULES_EXCEPT_MAIN",  
....
```

**Comment by panbonker** [comment]
it seems also that the logging wrapper prevents setting breakpoints inside the anon function
https://github.com/panifie/PingPong.jl/blob/3326d57cc8b8fcaeb66e5fc8b2d1c6a5342837dd/SimMode/src/backtest.jl#L49

not sure what to do with this

**Comment by janckerchen** [comment]
@panbonker  fond the solution for

> it seems also that the logging wrapper prevents setting breakpoints inside the anon function
> not sure what to do with this

1.  `cmd+, `, open vscode setting
2. search ` julia.debuggerDefaultCompiled`
3. click `Edit in settings.jon`,  vscode will open `settings.json` and auto append  `julia.debuggerDefaultCompiled` and default value.
4. add `-Base.CoreLogging` as screenshot 

> <img width="349" alt="image" src="https://github.com/panifie/PingPong.jl/assets/68181/24ff1719-203e-414e-be09-46faea469ff4">

5. now breakpoint is activited in  the logging wrapper  

> <img width="467" alt="image" src="https://github.com/panifie/PingPong.jl/assets/68181/4cf2268c-3f32-4ae9-94ea-d33953f9b833">
